name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel (production)
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_5ZkEvq9rISl82OyTnMff1QXo
          VERCEL_PROJECT_ID: prj_nPzlZ1qrCnCQDsiz3Vg9cxjPktN4
